Repository dshoreman/servidor, pull requests merged in 2019-10, with the labels that each got.

#151 Namespace the VueX modules to isolate searches
  CHANGELOG.md
  resources/js/components/Files/Browser/FileList.vue
  resources/js/components/Sites/Editor.vue
  resources/js/components/System/GroupEditor.vue
  resources/js/components/System/Groups.vue
  resources/js/components/System/UserEditor.vue
  resources/js/components/System/Users.vue
  resources/js/pages/Files/Browser.vue
  resources/js/pages/Files/Editor.vue
  resources/js/pages/Sites.vue
  resources/js/pages/Sites/Detail.vue
  resources/js/pages/Sites/Edit.vue
  resources/js/pages/Sites/List.vue
  resources/js/store/index.js
  resources/js/store/modules/FileManager.js
  resources/js/store/modules/Site.js
  resources/js/store/modules/System/Group.js
  resources/js/store/modules/System/User.js
Labels: bug

#157 Update Mix, Sass Loader and Cross-env
  package-lock.json
  package.json
Labels: depfu

#160 Fix Old file flickers before showing the current file #118
  resources/js/pages/Files/Editor.vue
  resources/js/store/modules/FileManager.js
Labels: enhancement

#159 Redirect to editor after application is created
  resources/js/pages/Sites.vue
  resources/js/store/modules/Site.js
Labels: bug

#162 Highlight user/group being edited
  resources/js/components/System/GroupItem.vue
  resources/js/components/System/Groups.vue
  resources/js/components/System/UserItem.vue
  resources/js/components/System/Users.vue
  resources/js/store/modules/System/Group.js
  resources/js/store/modules/System/User.js
  resources/sass/app.scss
  resources/sass/components/_listitem.scss
Labels: enhancement

#165 Fix issue with adding group to user
  app/Http/Controllers/System/UsersController.php
  tests/Feature/Api/System/Users/UpdateUserTest.php
Labels: bug

#167 Add basic database listing
  .env.example
  app/Database.php
  app/Http/Controllers/DatabaseController.php
  composer.json
  composer.lock
  config/database.php
  resources/js/pages/Databases.vue
  resources/js/store/index.js
  resources/js/store/modules/Database.js
  routes/api.php
  tests/Unit/DatabaseTest.php
Labels: enhancement

#163 Add CodeMirror
  package-lock.json
  package.json
  resources/js/pages/Files/Editor.vue
  resources/js/store/index.js
  resources/js/store/modules/FileEditor.js
  resources/sass/app.scss
  resources/sass/components/_codemirror.scss
Labels: enhancement

#174 Sites: Branch dropdown
  CHANGELOG.md
  app/Http/Controllers/SiteController.php
  resources/js/components/Sites/Editor.vue
  resources/js/store/modules/Site.js
  routes/api.php
Labels: enhancement
