Repository dshoreman/servidor, pull requests merged in 2020-10, with the labels that each got.

#278 Fix the installer when running in Vagrant
  Makefile
  README.md
  Vagrantfile
  build/installer/_install.sh
  setup.sh
Labels: enhancement

#276 Set file editor mode based on filename
  resources/js/store/modules/FileEditor.js
Labels: hacktoberfest-accepted

#287 Implement codemirror addons
  resources/js/pages/Files/Editor.vue
  resources/js/store/modules/FileEditor.js
  resources/sass/components/_codemirror.scss
Labels: enhancement, hacktoberfest-accepted

#290 Initialize `theme` in localStorage if unset
  resources/js/plugins/darkmode/index.js
Labels: enhancement, hacktoberfest-accepted
